### ISSUE TITLE
UV chromatogram for Quad-Orbitrap Q-Exactive with Vanquish

### ISSUE THREAD

**Issue by Lioscro** [ProteoWizard/pwiz#1163]
Hello!
I have a Quad-Orbitrap Q-Exactive instrument with the Vanquish uHPLC system, and this instrument is used to generate TIC and UV chromatograms. The problem was that msconvert could not extract the UV chromatograms from the .raw files generated from this machine. After digging through the code, I found that the `instrumentData.Units` is `MilliAbsorbanceUnits` and the `instrumentData.AxisLabelY` is `UV_VIS_1 mAU`. Because of this Y axis label, msconvert does not extract the chromatogram, as indicated in this section of the code.
https://github.com/ProteoWizard/pwiz/blob/master/pwiz/data/vendor_readers/Thermo/ChromatogramList_Thermo.cpp#L404

After changing
```c++
if (bal::ends_with(instrumentData.Units, "AbsorbanceUnits") && instrumentData.AxisLabelY.empty())
```
to
```c++
if (bal::ends_with(instrumentData.Units, "AbsorbanceUnits"))
```
I could correctly extract UV chromatogram data in expected format.
Would this be something we could add to msconvert?
I would be happy to open a pr.
Thanks,
Joseph

**Comment by chambm** [comment]
Hmm, I expect there was a reason I put the AxisLabelY empty condition on there, but I don't remember what it was. Probably because I had a file with AbsorbanceUnits but the AxisLabelY was NOT a UV chromatogram: like a pressure trace or something. I'd be ok with a PR that replaces `instrumentData.AxisLabelY.empty()` with `(instrumentData.AxisLabelY.empty() || bal::starts_with(instrumentData.AxisLabelY, "UV")`
