### ISSUE TITLE
Shimadzu SRM file: wrong time base

### ISSUE THREAD

**Issue by egauthierphy** [ProteoWizard/pwiz#1410]
I'm encountering a problem with the time base of a Shimadzu SRM file since upgrading Proteowizard. What was correctly reported as minutes (in 3.0.20204) is now wrongly reported as seconds (at least from 3.0.20364, I can't find an earlier installer). 

I'm pretty sure it is related to #1220 that changed this:
https://github.com/ProteoWizard/pwiz/blob/e99cc685e07828e52887e3e70e525adf6a2ed03f/pwiz/data/vendor_readers/Shimadzu/ChromatogramList_Shimadzu.cpp#L134
to this:
https://github.com/ProteoWizard/pwiz/blob/b731e28d68433b4b017a69b9e69e632197f3bcf5/pwiz/data/vendor_readers/Shimadzu/ChromatogramList_Shimadzu.cpp#L134

Here is my data file: https://we.tl/t-2HuZRGB54p

The previous pull #1071 correctly fixed the TIC timing from minutes to seconds, however the SRM timing still need to be minutes, at least in the case of our data files from our 8060 MS. Did you change it to support newer data files?

**Comment by chambm** [comment]
The units have changed but the values assigned to those units have also changed due to the API. Your file looks reasonable in SeeMS. Top pane is all the SRM chromatograms overlaid, and the bottom pane is the TIC chromatogram:
![image](https://user-images.githubusercontent.com/5011937/104648446-22d3ae00-5681-11eb-942a-d475695b29e7.png)
SeeMS is converting the units to minutes here, but if looking at the mzML they'd be represented as seconds. Your file's GeneratedDateTime and ModifiedDateTime (the ones stored in the file, not the NTFS properties) are different by ~6.5 minutes, which is the length of the gradient SeeMS is showing, so it all seems correct.
