### ISSUE TITLE
What's the command line parameter for TPP compability?

### ISSUE THREAD

**Issue by gzu300** [ProteoWizard/pwiz#2092]
What's the command line parameter for TPP compability?

**Comment by chambm** [comment]
--filter "titleMaker &lt;RunId&gt;.&lt;ScanNumber&gt;.&lt;ScanNumber&gt;.&lt;ChargeState&gt; File:&quot;&lt;SourcePath&gt;&quot;, NativeID:&quot;&lt;Id&gt;&quot;

Actually passing this on the Windows command-line can be quite tricky though due to the weirdness of quote escaping. Something like:
`--filter "titleMaker <RunId>.<ScanNumber>.<ScanNumber>.<ChargeState> File:"""^<SourcePath^>""", NativeID:"""^<Id^>"""`

The latest versions of MSConvertGUI have a "Show Commandline" button that will get you the exact command-line to do what the GUI is doing.
