### ISSUE TITLE
Intensity scale changes of Sciex data after centroiding data

### ISSUE THREAD

**Issue by rickhelmus** [ProteoWizard/pwiz#409]
Hello,

When I use msconvert to convert TripleTOF 5600 Sciex data (GUI or command line, using a recent build) to mzML files the intensity scale seems to change to much lower values (several orders of magnitude):
<img width="957" alt="int-conversion" src="https://user-images.githubusercontent.com/37015911/50770733-98cdff00-1288-11e9-93c5-ebec09902286.PNG">
Interestingly, the TIC/BPC values reported for each scan seem to be unaffected.

If I use `qtofpeakpicker` instead of vendor centroiding this doesn't occur. Does anyone else have experience with this?

Thanks,
Rick

**Comment by qiangziMS** [comment]
I've also experienced this problem, and not only the scale changed, the ratio of peaks also changed. It seems like a version problem, when use old version of msconvert, every thing is OK ...

**Comment by rickhelmus** [comment]
Hmm interesting! Any way you could share your old version? Unless I am missing something it seems that TeamCity doesn't s retain older versions...

**Comment by chambm** [comment]
Vendor centroiding with Sciex uses area as the intensity rather than apex height. The Sciex people consider this more accurate and we changed it at their request. The centroid x value is certainly not the same as the apex x value. This was changed back in 2016.

CWT peak picker currently always gives the apex x value and intensity (and not even an interpolated apex of the wavelet, it's whatever the closest datapoint is).
